"""users approved_at

Revision ID: 781aa055c902
Revises: 7aead40964fd
Create Date: 2026-09-23 16:18:23.208921

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '781aa055c902'
down_revision = '7aead40964fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('approved_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###

    # Перенос данных: уже активные пользователи (админ, одобренные вручную)
    # считаются одобренными. Точного времени одобрения нет — берём время
    # регистрации. Неактивные остаются заявками (approved_at = NULL).
    op.execute("UPDATE users SET approved_at = created_at WHERE is_active")


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('approved_at')

    # ### end Alembic commands ###
